In [1]:
import numpy as np

In [2]:
#membuat bilangan distribusi uniform / random dari (0-1)
np.random.rand(7)

array([0.70202778, 0.1197799 , 0.75993514, 0.49739785, 0.03699985,
       0.35003721, 0.07890082])

In [3]:
#membuat bilangan distribusi uniform matriks 2 dimensi
np.random.rand(5,2) #5 baris 2 kolom

array([[0.09895538, 0.14549273],
       [0.05993805, 0.01146473],
       [0.15845933, 0.50763992],
       [0.4899287 , 0.58525701],
       [0.20598971, 0.86144423]])

In [4]:
#Bilangan distribusi normal (gaussian) antara mulai dari -tak hingga sampai +tak hingga
np.random.randn(10)

array([ 0.11522456, -0.01487886, -0.72773877, -0.29860185, -0.51163794,
       -0.10472433, -0.19274905, -1.83972335,  1.45652584,  0.55141083])

In [5]:
#Bilangan distribusi normal (gaussian) matriks 2 dimensi
np.random.randn(10,5)

array([[ 0.67880798, -0.91816087, -0.12633597,  1.05993706,  0.29097972],
       [ 0.06618738, -0.84020471,  0.25064993,  1.37350676, -0.26510519],
       [ 1.06230526,  1.86412655, -0.4976814 , -1.31283663,  1.26802061],
       [ 0.55358958, -0.32317249,  0.84562184, -0.7019325 ,  0.49892374],
       [ 0.49287348, -0.22316287,  0.57960189, -0.49876051, -0.67154152],
       [-1.19919723,  0.06305152,  0.31875015,  0.58004422, -0.68425885],
       [-0.13970103,  1.04644154, -0.16997469, -0.07865958, -0.10033228],
       [ 0.52606233,  1.13527428, -1.44900456,  0.19773126, -0.6279387 ],
       [-0.83232125,  0.55302206,  2.03963303, -0.72517898, -1.33000066],
       [ 1.56955068,  0.27438358,  0.05897585, -1.3814209 ,  0.3350606 ]])