## Indexing in Numpy

In [1]:
import numpy as np

In [3]:
coba = np.arange(0,11)

In [4]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#indexing
coba[6]

6

In [10]:
#slicing
coba[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
coba[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
coba[2:6]

array([2, 3, 4, 5])

In [14]:
#jika di python biasa kita tidak dapat mengganti variable 
#dalam numpy dapat mengganti variable yang merujuk variable lain
coba2 = coba[:6] #child dari coba

In [15]:
coba2 

array([0, 1, 2, 3, 4, 5])

In [20]:
coba2[:] = 100 #contoh mengganti nya

In [21]:
coba2

array([100, 100, 100, 100, 100, 100])

In [23]:
#ketika child di ganti maka juga akan mengganti parent
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [25]:
#function yang di gunakan agar variable berdiri sendiri 
coba3 = coba.copy()

In [26]:
coba3

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [27]:
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [28]:
coba3[:] = 20

In [29]:
coba3

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [30]:
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [31]:
#contoh indexing dalam array
bilangan = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
bilangan

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
#indexing dalam python
bilangan[2]

array([7, 8, 9])

In [36]:
bilangan[1][2]

6

In [37]:
bilangan[0][0]

1

In [39]:
#indexing dalam numpy
bilangan[1,2]

6

In [40]:
bilangan[0,0]

1

In [45]:
#slicing di matriks multidimensional
bilangan[2,1:]

array([8, 9])

In [49]:
bilangan[1:2,0:2]

array([[4, 5]])

In [50]:
bilangan[0:1,1:2]

array([[2]])