# Numpy

numpy ialah library aljabar linear untuk python

In [1]:
#import library numpy 
import numpy as np

In [2]:
angka = [1,2,3,4,5]

In [3]:
#merubah list menjadi array menggunakan numpy
angkanp = np.array(angka)
#agar dapat melakukan operasi bilangan

In [4]:
angkanp

array([1, 2, 3, 4, 5])

In [7]:
#menggunakan list biasa
angka*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [6]:
#menggunakan np
angkanp*10

array([10, 20, 30, 40, 50])

In [8]:
angka2 = [[1,2,3],[4,5,6],[7,8,9]] 

In [12]:
angka2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
angka2np = np.array(angka2)

In [10]:
#contoh matriks 3 x 3 baris dikali kolom
angka2np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#fungsi numpy untuk membuat array
np.arange(0,11) #mirip slicing python biasa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(0,31,) #dengan jarak

array([ 0,  6, 12, 18, 24, 30])

In [22]:
#fungsi numpy untuk generate 0. / membangkitkan angka 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
#untuk multidimensional array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
#fungsi untuk membangkitkan angka 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
#fungsi yang hampir sama dengan arrange
#tapi mengikutkan indeks terakhir
#dan juga membagi jarak sama rata sesuai yang di mau
#pertama = dimulai, kedua = berakhir, tiga = dibagi berapa 
np.linspace(1,5,10) 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
#fungsi untuk identity matriks
#membuat matriks sama baris dan kolom
#dan membuat diagonal angka 1 didalamnya
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])