### Random Integer

In [8]:
import numpy as np

In [9]:
#mengenerate integer
bilangan = np.random.randint(1,10,10) #1 = mulai, 10 = akhir, 10 = banyak generate

In [10]:
bilangan

array([6, 8, 8, 6, 6, 3, 7, 8, 1, 7])

In [11]:
#dalam randint indeks terakhir tidak di ikutkan
coba = np.random.randint(0,10,20).reshape(5,4)

In [12]:
coba

array([[4, 3, 4, 4],
       [1, 3, 2, 3],
       [3, 6, 5, 6],
       [4, 1, 0, 3],
       [2, 9, 4, 9]])

In [13]:
coba.reshape(2,10) #hanya mengubah struktur matriks ke 2 x 10

array([[4, 3, 4, 4, 1, 3, 2, 3, 3, 6],
       [5, 6, 4, 1, 0, 3, 2, 9, 4, 9]])