## Slicing with Boolean

In [1]:
import numpy as np

In [16]:
bilangan = np.arange(1,11)

In [17]:
bilangan

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#cara lama
true_angka = bilangan < 5 #filter yang di ingin kan

In [12]:
true_angka

array([ True,  True,  True,  True])

In [13]:
bilangan = bilangan[true_angka] #yang true dimasukan kedalam bilangan

In [14]:
bilangan

array([1, 2, 3, 4])

In [18]:
#cara cepat 
bilangan = bilangan[bilangan < 5]

In [19]:
bilangan

array([1, 2, 3, 4])